#!/usr/bin/env python3

import argparse
import csv
import gzip
import json
import os
import re
import sqlite3
import sys
import time

def download_files(arg):
	os.system(f'mkdir -p {arg.build}')
	if not os.path.exists(f'{arg.build}/mgi_gpi.gz'):
		os.system(f'curl {arg.mgi_gpi} > {arg.build}/mgi_gpi.gz')
	if not os.path.exists(f'{arg.build}/mgi_gaf.gz'):
		os.system(f'curl {arg.mgi_gaf} > {arg.build}/mgi_gaf.gz')
	if not os.path.exists(f'{arg.build}/go_basic.json.gz'):
		os.system(f'curl {arg.go_basic} | gzip > {arg.build}/go_basic.json.gz')
	if not os.path.exists(f'{arg.build}/mp.json.gz'):
		os.system(f'curl {arg.mp} | gzip > {arg.build}/mp.json.gz')
	if not os.path.exists(f'{arg.build}/mmrrc.gz'):
		sys.exit('need to do this automatically, need URL')

def create_database(arg):
	if os.path.exists(arg.database): sys.exit('database already exists')
	con = sqlite3.connect(arg.database)
	cur = con.cursor()

	# go_nodes table from go_basic.json.gz
	cur.execute('CREATE TABLE go_nodes(go_id PRIMARY KEY, label, desc)')
	with gzip.open(f'{arg.build}/go_basic.json.gz', 'rt') as fp:
		data = json.load(fp)
	for record in data['graphs'][0]['nodes']:
		m = re.search(r'(GO_\d+)', record['id'])
		if not m: continue
		if 'deprecated' in record['meta']: continue
		go_id = m.group(1)
		go_id = record['id'].split('/')[4]
		label = record['lbl']
		desc = record['meta']['definition']['val']
		cur.execute(f'INSERT INTO go_nodes VALUES ("{go_id}", "{label}", "{desc}")')
	con.commit()

	# mp table from mp.json.gz (variant of above not worth abstracting)
	cur.execute('CREATE TABLE mp(mp_id PRIMARY KEY, label, desc)')
	with gzip.open(f'{arg.build}/mp.json.gz', 'rt') as fp:
		data = json.load(fp)
	for record in data['graphs'][0]['nodes']:
		if 'meta' not in record: continue
		m = re.search(r'(MP_\d+)', record['id'])
		if not m: continue
		if 'deprecated' in record['meta']: continue
		mp_id = m.group(1)
		label = record['lbl']
		desc = record['meta']['definition']['val'] if 'definition' in record['meta'] else ''
		cur.execute(f'INSERT INTO mp VALUES ("{mp_id}", "{label}", "{desc}")')
	con.commit()

	# genes table from mgi_gpi.gz
	cur.execute('CREATE TABLE genes(symbol PRIMARY KEY, mgi_id UNIQUE, desc)')
	with gzip.open(f'{arg.build}/mgi_gpi.gz', 'rt') as fp:
		for line in fp:
			if line.startswith('!'): continue
			f = line.split('\t')
			mgi, symbol, desc = f[0], f[1], f[2]
			m = re.match(r'MGI:(MGI:\d+)', mgi)
			if not m: continue
			mgi_id = m.group(1)
			cur.execute(f'INSERT OR IGNORE INTO genes VALUES ("{symbol}", "{mgi_id}", "{desc}")')
	con.commit()

	# mgi2go table from mgi_gaf.gz
	cur.execute('CREATE TABLE mgi2go(mgi_id, go_id)')
	cur.execute('CREATE INDEX idx1 ON mgi2go(mgi_id)')
	cur.execute('CREATE INDEX idx2 ON mgi2go(go_id)')
	with gzip.open(f'{arg.build}/mgi_gaf.gz', 'rt') as fp:
		for line in fp:
			if line.startswith('!'): continue
			f = line.split('\t')
			mgi_id, go_id = f[1], f[4]
			if not re.match(r'MGI:\d+', mgi_id): continue
			go_id = go_id.replace(':', '_')
			cur.execute(f'INSERT INTO mgi2go VALUES ("{mgi_id}", "{go_id}")')
	con.commit()

	# mmrrc2mgi, mmrrc2mp tables from mmrrc.gz
	data = {}
	with gzip.open(f'{arg.build}/mmrrc.gz', 'rt') as fp:
		header = next(fp)
		for row in csv.reader(fp, delimiter=','):
			mmrrc_id = row[0]
			mgi_id = row[10]
			mp_txt = row[15]
			if mmrrc_id not in data:
				data[mmrrc_id] = {'mgi': set(), 'mp': set(), 'go': set()}
			if mgi_id != '': data[mmrrc_id]['mgi'].add(mgi_id)
			if mp_txt != '': data[mmrrc_id]['mp'].add(mp_txt)

	cur.execute('CREATE TABLE mmrrc2mgi(mmrrc_id, mgi_id)')
	cur.execute('CREATE INDEX idx3 ON mmrrc2mgi(mmrrc_id)')
	cur.execute('CREATE INDEX idx4 ON mmrrc2mgi(mgi_id)')
	for mmrrc_id in data:
		for mgi_id in data[mmrrc_id]['mgi']:
			cur.execute(f'INSERT INTO mmrrc2mgi VALUES ("{mmrrc_id}", "{mgi_id}")')
	con.commit()

	cur.execute('CREATE TABLE mmrrc2mp(mmrrc_id, mp_id)')
	cur.execute('CREATE INDEX idx5 ON mmrrc2mp(mmrrc_id)')
	cur.execute('CREATE INDEX idx6 ON mmrrc2mp(mp_id)')
	for mmrrc_id in data:
		if len(data[mmrrc_id]['mp']) == 0: continue
		mp_txt = data[mmrrc_id]['mp'].pop() # there is only 1
		for m in re.finditer(r'MP:\d+', mp_txt):
			mp_id = m.group()
			mp_id = mp_id.replace(':', '_')
			cur.execute(f'INSERT INTO mmrrc2mp VALUES ("{mmrrc_id}", "{mp_id}")')
	con.commit()

	# mmrrc2gene table
	cur.execute('CREATE TABLE mmrrc2gene(mmrrc_id, symbol)')
	cur.execute('CREATE INDEX idx7 ON mmrrc2gene(mmrrc_id)')
	cur.execute('CREATE INDEX idx8 ON mmrrc2gene(symbol)')
	for mmrrc_id in data:
		for mgi_id in data[mmrrc_id]['mgi']:
			r = cur.execute(f'SELECT symbol from genes WHERE mgi_id="{mgi_id}"').fetchall()
			symbols = set()
			for x in r: symbols.add(x[0])
			for symbol in symbols:
				cur.execute(f'INSERT INTO mmrrc2gene VALUES ("{mmrrc_id}", "{symbol}")')
	con.commit()

	# mmrrc2go table
	cur.execute('CREATE TABLE mmrrc2go(mmrrc_id, go_id)')
	cur.execute('CREATE INDEX idx9 ON mmrrc2go(mmrrc_id)')
	cur.execute('CREATE INDEX idx10 ON mmrrc2go(go_id)')
	for mmrrc_id in data:
		for mgi_id in data[mmrrc_id]['mgi']:
			r = cur.execute(f'SELECT go_id from mgi2go WHERE mgi_id="{mgi_id}"').fetchall()
			go_ids = set()
			for x in r: go_ids.add(x[0])
			for go_id in go_ids:
				cur.execute(f'INSERT INTO mmrrc2go VALUES ("{mmrrc_id}", "{go_id}")')
	con.commit()

def test(arg):
	con = sqlite3.connect(f'file:{arg.database}?mode=ro', uri=True)
	cur = con.cursor()

	# get some random identifiers for testing
	symbols = [x[0] for x in cur.execute(f'SELECT symbol FROM genes ORDER BY RANDOM() LIMIT {arg.limit}').fetchall()]

	mgi_ids = [x[0] for x in cur.execute(f'SELECT mgi_id FROM genes ORDER BY RANDOM() LIMIT {arg.limit}').fetchall()]

	go_ids = [x[0] for x in cur.execute(f'SELECT go_id FROM go_nodes ORDER BY RANDOM() LIMIT {arg.limit}').fetchall()]

	mp_ids = [x[0] for x in cur.execute(f'SELECT mp_id FROM mp ORDER BY RANDOM() LIMIT {arg.limit}').fetchall()]

	mmrrc_ids = [x[0] for x in cur.execute(f'SELECT mmrrc_id FROM mmrrc2mgi ORDER BY RANDOM() LIMIT {arg.limit}').fetchall()]

	# mmrrc2gene
	t0 = time.time()
	for symbol in symbols:
		r = cur.execute(f'SELECT * FROM mmrrc2gene WHERE symbol="{symbol}"').fetchall()
		if arg.verbose: print(symbol, r)
	t1 = time.time()
	print(f'{arg.limit} symbol -> mmrrc_id', t1 - t0)

	t0 = time.time()
	for mmrrc_id in mmrrc_ids:
		r = cur.execute(f'SELECT * FROM mmrrc2gene WHERE mmrrc_id="{mmrrc_id}"').fetchall()
		if arg.verbose: print(mmrrc_id, r)
	t1 = time.time()
	print(f'{arg.limit} mmrrc_id -> symbol', t1 - t0)

	# mmrrc2go
	t0 = time.time()
	for go_id in go_ids:
		r = cur.execute(f'SELECT * FROM mmrrc2go WHERE go_id="{go_id}"').fetchall()
		if arg.verbose: print(go_id, r)
	t1 = time.time()
	print(f'{arg.limit} go_id -> mmrrc_id', t1 - t0)

	t0 = time.time()
	for mmrrc_id in mmrrc_ids:
		r = cur.execute(f'SELECT * FROM mmrrc2go WHERE mmrrc_id="{mmrrc_id}"').fetchall()
		if arg.verbose: print(mmrrc_id, r)
	t1 = time.time()
	print(f'{arg.limit} mmrrc_id -> go_id', t1 - t0)

	# mmrrc2mp
	t0 = time.time()
	for mp_id in mp_ids:
		r = cur.execute(f'SELECT * FROM mmrrc2mp WHERE mp_id="{mp_id}"').fetchall()
		if arg.verbose: print(mp_id, r)
	t1 = time.time()
	print(f'{arg.limit} mp_id -> mmrrc_id', t1 - t0)

	t0 = time.time()
	for mmrrc_id in mmrrc_ids:
		r = cur.execute(f'SELECT * FROM mmrrc2mp WHERE mmrrc_id="{mmrrc_id}"').fetchall()
		if arg.verbose: print(mmrrc_id, r)
	t1 = time.time()
	print(f'{arg.limit} mmrrc_id -> mp_id', t1 - t0)

#########
## CLI ##
#########

parser = argparse.ArgumentParser(description='GO to MMRRC database utility')
sub = parser.add_subparsers(required=True, help='sub-commands')

## download sub-command ##
sub1 = sub.add_parser('download', help='download MMRRC and MGI files')
sub1.add_argument('--mmrrc', required=False, metavar='<url>',
	default='https://www.mmrrc.org/...',
	help='[%(default)s]')
sub1.add_argument('--mgi_gpi', required=False, metavar='<url>',
	default='https://current.geneontology.org/annotations/mgi.gpi.gz',
	help='URL to MGI GPI file [%(default)s]')
sub1.add_argument('--mgi_gaf', required=False, metavar='<url>',
	default='https://current.geneontology.org/annotations/mgi.gaf.gz',
	help='URL TO MGI GAF file [%(default)s]')
sub1.add_argument('--go_basic', required=False, metavar='<url>',
	default='https://current.geneontology.org/ontology/go-basic.json',
	help='URL to GO basic json [%(default)s]')
sub1.add_argument('--mp', required=False, metavar='<url>',
	default='https://www.informatics.jax.org/downloads/reports/mp.json',
	help='URL to mammalian phenotype json')
sub1.add_argument('--build', required=False, metavar='<dir>',
	default='build', help='directory for temp files [%(default)s]')
sub1.set_defaults(func=download_files)

## create sub-command ##
sub2 = sub.add_parser('create', help='make database')
sub2.add_argument('--build', required=False, metavar='<dir>',
	default='build', help='directory of temp files [%(default)s]')
sub2.add_argument('--database', required=False, metavar='<file.db>',
	default='mmsearch.db', help='database [%(default)s]')
sub2.add_argument('--testing', action='store_true')
sub2.set_defaults(func=create_database)

## test sub-command ##
sub3 = sub.add_parser('test', help='internal testing')
sub3.add_argument('--database', required=False, metavar='<file.db>',
	default='mmsearch.db', help='database [%(default)s]')
sub3.add_argument('--limit', required=False, metavar='<int>',
	default=1000, help='number of searches to perform [%(default)i]')
sub3.add_argument('--verbose', action='store_true')
sub3.set_defaults(func=test)

## finish up ##
arg = parser.parse_args()
arg.func(arg)
